version: "3.9"

services:
  nobita:
    image: nobita
    container_name: nobita
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    environment:
      CONFIG_FILE_URL: $CONFIG_FILE_URL
    restart: on-failure

  # restarter:
  #   image: docker:cli
  #   volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
  #   command: ["/bin/sh", "-c", "while true; do sleep 259200; docker restart nobita; done"]
  #   restart: on-failure
